/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package war;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//        Card card = new Card();
//        System.out.println("card = " + card);
    }
}
